import { eslintConfig } from "@broccoli/config/eslint";
import reactHooks from "eslint-plugin-react-hooks";
import { reactRefresh } from "eslint-plugin-react-refresh";
import { defineConfig, globalIgnores } from "eslint/config";

export default defineConfig(
  eslintConfig(import.meta.dirname),
  globalIgnores(["src/routeTree.gen.ts"]),
  reactHooks.configs.flat.recommended,
  // Route files export `Route` next to their components, as TanStack Router expects.
  reactRefresh.configs.vite({ allowExportNames: ["Route"] }),
  {
    // Generated by the shadcn CLI, which exports variants next to components.
    files: ["src/components/ui/**"],
    rules: { "react-refresh/only-export-components": "off" },
  },
  {
    rules: {
      "no-restricted-imports": [
        "error",
        {
          // `shadcn add` sometimes writes this import (and adds an unrelated `cn` package).
          paths: [{ name: "cn", message: 'Import cn from "@/lib/class-names".' }],
        },
      ],
    },
  },
);
