import { eslintConfig } from "@broccoli/config/eslint";
import graphql from "@graphql-eslint/eslint-plugin";
import reactHooks from "eslint-plugin-react-hooks";
import { reactRefresh } from "eslint-plugin-react-refresh";
import { defineConfig, globalIgnores } from "eslint/config";

export default defineConfig(
  eslintConfig(import.meta.dirname),
  globalIgnores(["src/__generated__/"]),
  {
    files: ["**/*.{js,ts,tsx}"],
    extends: [
      reactHooks.configs.flat.recommended,
      // Route files export `Route` next to their components, as TanStack Router expects.
      reactRefresh.configs.vite({ allowExportNames: ["Route"] }),
    ],
  },
  {
    // Generated by the shadcn CLI, which exports variants next to components.
    files: ["src/components/ui/**"],
    rules: { "react-refresh/only-export-components": "off" },
  },
  {
    rules: {
      "no-restricted-imports": [
        "error",
        {
          // `shadcn add` sometimes writes this import (and adds an unrelated `cn` package).
          paths: [{ name: "cn", message: 'Import cn from "@/lib/class-names".' }],
        },
      ],
    },
  },
  {
    files: ["src/**/*.graphql"],
    languageOptions: {
      parser: graphql.parser,
      parserOptions: {
        graphQLConfig: { schema: "../api/src/**/*.graphql", documents: "src/**/*.graphql" },
      },
    },
    plugins: { "@graphql-eslint": graphql },
    rules: {
      // Every query selects `id`, so the normalised cache can identify each object.
      "@graphql-eslint/require-selections": "error",
      "@graphql-eslint/executable-definitions": "error",
      "@graphql-eslint/fields-on-correct-type": "error",
      "@graphql-eslint/known-argument-names": "error",
      "@graphql-eslint/known-type-names": "error",
      "@graphql-eslint/no-undefined-variables": "error",
      "@graphql-eslint/no-unused-fragments": "error",
      "@graphql-eslint/no-unused-variables": "error",
      "@graphql-eslint/unique-operation-name": "error",
    },
  },
);
